# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-10-10 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
    ]
